ci: add some tests
geprog/use-feathers pull request #36
Opened 2021-07-30 15:38 UTC by anbraten

2021-07-30 19:01 UTC, anbraten commented
@lukashass Any idea why the service type is broken?

2021-07-30 21:47 UTC, lukashass commented
> @lukashass Any idea why the service type is broken?

No but there is already an issue for that #1

2021-07-30 21:55 UTC, lukashass approved these changes, later dismissed

2021-07-30 21:55 UTC, lukashass commented on package.json
>      "test:watch": "yarn test --watch",
```suggestion
    "test:watch": "yarn test --watch",
    "typecheck": "tsc --noEmit",
```

2021-08-06 15:07 UTC, lukashass requested changes

2021-08-06 15:07 UTC, lukashass commented on package.json
>      "esbuild-register": "2.6.0",
@anbraten I think this can be removed

2021-08-06 15:11 UTC, lukashass commented on package.json
>      "esbuild-register": "2.6.0",
```suggestion
```

2021-08-06 15:26 UTC, anbraten commented on package.json
>      "esbuild-register": "2.6.0",
@lukashass removed it

2021-08-06 15:30 UTC, lukashass approved these changes

2021-08-06 15:30 UTC, merged